export enum STATUS_ORDER {
  PROCESSING = "PROCESSING",
  DELIVERING = "DELIVERING",
  WAIT_FOR_PAYMENT = "WAIT_FOR_PAYMENT",
  CANCELED = "CANCELED",
  SUCCESS = "SUCCESS",
}

export interface StatusOrder {
  typeStatus:
    | STATUS_ORDER.PROCESSING
    | STATUS_ORDER.DELIVERING
    | STATUS_ORDER.WAIT_FOR_PAYMENT
    | STATUS_ORDER.CANCELED
    | STATUS_ORDER.SUCCESS;
}
